mp3000mp_tos.show_last:
  path: /
  controller: Mp3000mp\TOSBundle\Controller\Mp3000mpTOSController::index
  methods: GET
mp3000mp_tos.post:
  path: /
  controller: Mp3000mp\TOSBundle\Controller\Mp3000mpTOSController::sign
  methods: POST
