language: php

php:
  - 7.3

# todo tester plusieurs version de Symfony

script:
  - composer install
  - composer run cs
  - composer run ps
  - composer run tuc

after_success:
  - travis_retry php vendor/bin/php-coveralls -v --exclude-no-stmt
